# Site settings_dirc
title: SideQuest Productions
description: > #
  SideQuest is a company founded by a few nerd weirdos trying to make honestly good nerd weirdo stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sidequest.productions" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css/_sass
  style: :expanded
